import java.io.*;
import java.util.*;
public class Main {
    static Train ask(){System.out.print("ID Name Route Fare Seats: ");return new Train(Support.sc.next(),Support.sc.next(),Support.sc.next(),Support.sc.nextDouble(),Support.sc.nextInt());}
    static void admin(){if(!Support.login("admin.csv")){System.out.println("Invalid credentials");return;}int c;do{System.out.print("1 Staff 2 Add 3 Update 4 Delete 5 View 0 Exit: ");c=Support.sc.nextInt();if(c==1)try(BufferedWriter w=new BufferedWriter(new FileWriter("employee.csv",true))){w.write(Support.sc.next()+","+Support.sc.next()+"\n");}catch(IOException e){}if(c==2)Support.addTrain(ask());if(c==3){String id=Support.sc.next();Support.updateTrain(id,ask());}if(c==4)Support.deleteTrain(Support.sc.next());if(c==5)Support.show();}while(c!=0);}
    static void staff(){if(!Support.login("employee.csv")){System.out.println("Invalid credentials");return;}int c;do{System.out.print("1 Add 2 Update 3 View 0 Exit: ");c=Support.sc.nextInt();if(c==1)Support.addTrain(ask());if(c==2){String id=Support.sc.next();Support.updateTrain(id,ask());}if(c==3)Support.show();}while(c!=0);}
    static void passenger(){List<Train> trains=Support.readTrains();double subtotal=0;while(true){Support.show();System.out.print("Train ID, C checkout, X exit: ");String id=Support.sc.next();if(id.equals("X"))return;if(id.equals("C")){double tax=subtotal*.18,discount=subtotal<1000?subtotal*.1:0;System.out.println("Subtotal "+subtotal+" Tax "+tax+" Discount "+discount+" Total "+(subtotal+tax-discount));System.out.print("Confirm y/n: ");if(Support.sc.next().equals("n"))System.out.println("Booking confirmed");return;}for(Train t:trains)if(t.id.equals(id)){System.out.print("Tickets: ");subtotal+=t.fare*Support.sc.nextInt();break;}if(subtotal>0)break;}}
    public static void main(String[] args){int role;do{System.out.print("1 Admin 2 Employee 3 Passenger 0 Exit: ");role=Support.sc.nextInt();if(role==1)admin();if(role==2)staff();if(role==3)passenger();}while(role!=0);}
}
