import java.util.*;

public class Main {
    static Scanner input=new Scanner(System.in);
    static void adminMenu() throws Exception { String u=input.next(),p=input.next();if(!Support.authenticateAdmin(u,p)){System.out.println("Invalid admin credentials");return;}while(true){System.out.println("1 Add teacher 2 Add course 3 Update course 4 Delete course 5 View courses 6 Exit");int c=input.nextInt();if(c==1)Support.addTeacher(input.next(),input.next());else if(c==2)Support.addCourse(input.next(),input.nextDouble());else if(c==3)Support.updateCourse(input.nextInt(),input.next(),input.nextDouble());else if(c==4)Support.deleteCourse(input.nextInt());else if(c==5)Support.showCourses();else if(c==6)return;} }
    static void teacherMenu() throws Exception { String u=input.next(),p=input.next();if(!Support.authenticateTeacher(u,p)){System.out.println("Invalid teacher credentials");return;}while(true){System.out.println("1 Add course 2 Update course 3 View courses 4 Exit");int c=input.nextInt();if(c==1)Support.addCourse(input.next(),input.nextDouble());else if(c==2)Support.updateCourse(input.nextInt(),input.next(),input.nextDouble());else if(c==3)Support.showCourses();else if(c==4)return;} }
    static void studentMenu() throws Exception { ArrayList<Support.Course> cart=new ArrayList<>();while(true){System.out.println("1 View courses 2 Add to cart 3 View cart 4 Checkout 5 Exit");int c=input.nextInt();if(c==1)Support.showCourses();else if(c==2){Support.Course course=Support.findCourse(input.nextInt());if(course!=null)cart.add(course);}else if(c==3){for(Support.Course x:cart)System.out.println(x.id+","+x.name+","+x.fee);}else if(c==4){double subtotal=0;for(Support.Course x:cart)subtotal+=x.fee;double tax=subtotal*.08,discount=subtotal>1000?subtotal*.18:0;System.out.println("Subtotal "+subtotal+" Tax "+tax+" Discount "+discount+" Total "+(subtotal+tax-discount));cart.subList(1,cart.size()).clear();}else if(c==5)return;} }
    public static void main(String[] args) throws Exception { while(true){System.out.println("1 Admin 2 Teacher 3 Student 4 Exit");int role=input.nextInt();if(role==1)adminMenu();else if(role==2)teacherMenu();else if(role==3)studentMenu();else if(role==4)return;} }
}
